### ISSUE TITLE
Add Ignoring Subheaders feature like docsify sidebar config.

### ISSUE THREAD

**Issue by nanoia** [justintien/docsify-plugin-toc#14]
By adding some tag like `<!-- {docsify-toc-ignore} -->` or `<!-- {docsify-toc-ignore-all} -->` to ignore a specific header or  ignore all headers on a specific page like docsify sidebar custome config.
https://docsify.js.org/#/more-pages?id=ignoring-subheaders

**Comment by justintien** [comment]
@nanoia 

I added on v1.3.2

see: https://github.com/justintien/docsify-plugin-toc

About options.ignoreHeaders = []. (You can set anythings..)

**Comment by dror-weiss** [comment]
Hi,

Thanks, I need this feature as well.

Some open issues in my opinion:
- It doesn't work in any form, a working example would be greatly appreciated.
- Do you support ignore-all?
- v1.3.2 not published
- You have mistakenly added a `console.error` if there is an ignoreError. I think you didn't mean to console anything ...
