### ISSUE TITLE
unable to add H1 headings to the TOC

### ISSUE THREAD

**Issue by cuotos** [justintien/docsify-plugin-toc#2]
I want this TOC to contain every heading including the H1.

But if I prefix `target: 'h1, h2, h3...`  H1 headings still do not show.

Without this, the new TOC shows all the h2+ headings, but misses the h1s.

for a page with the layout

```
# Section A
## subA1
## subA2

# Section B
## subB1
## subB2
```

The toc shows as 

```
subA1
subA2
subB1
subB2
```

With no indication that there is a major separator between them

**Comment by cuotos** [comment]
https://github.com/justintien/docsify-plugin-toc/blob/eec2582b9580d4871b5777ab088ce5ed501d0205/src/toc.js#L28

should be
`level >= 1` 

?

**Comment by justintien** [comment]
@cuotos Support `h1` on v1.2.0
