### ISSUE TITLE
How to modify script CSS?

### ISSUE THREAD

**Issue by stigmollerhansen** [justintien/docsify-plugin-toc#5]
In my document's `<head>` I am loading a stylesheet with my custom tweaks to the ToC script's CSS. However, my changes are overridden by the script's own embedded CSS as it is imported using the suggested `<script src="https://unpkg.com/docsify-plugin-toc"></script>` at the end of my document.

How do I override the CSS provided with the script?

**Comment by justintien** [comment]
@stigmollerhansen


I am glad to inform you that in the latest release of `v1.3.1`.

You will be able to easily override the css style

See README
https://github.com/justintien/docsify-plugin-toc
