### ISSUE TITLE
it will be better to support the custom TOC text color in Configure 

### ISSUE THREAD

**Issue by junxnone** [justintien/docsify-plugin-toc#7]
- **Thanks for share awesome plugin.**

---
- **The TOC default text color is black. It is incompatible with dark mode**
https://github.com/justintien/docsify-plugin-toc/blob/1f6775072381519d6cb98af0b74e0eb314222024/src/main.css#L78
https://github.com/justintien/docsify-plugin-toc/blob/1f6775072381519d6cb98af0b74e0eb314222024/src/main.css#L57
https://github.com/justintien/docsify-plugin-toc/blob/1f6775072381519d6cb98af0b74e0eb314222024/src/main.css#L68
- **Dark mode incompatible  example**
![image](https://user-images.githubusercontent.com/2216970/148524327-0485db1e-280c-4c82-81c3-fd7021607f5e.png)

**Comment by BruceLee569** [comment]
For solve this problem, I add a delay function into <script> tag :
```javascript
    setInterval(function () {
        var toc_text_color = getComputedStyle(document.querySelector('main')).getPropertyValue('color-scheme') === 'dark' ? 'white' : 'black'
        document.querySelectorAll('.page_toc a').forEach(
            function (e) {
                e.style.color = toc_text_color
            }
        )
    }, 100);
```

**Comment by justintien** [comment]
@junxnone 

I am glad to inform you that in the latest release of v1.3.1.

You will be able to easily override the css style

See README
https://github.com/justintien/docsify-plugin-toc

If you are interested you can also contribute to the theme.
